### ISSUE TITLE
Bug: "about yourself" keeps rendering after changing to another page.

### ISSUE THREAD

**Issue by fabriph** [AVatch/unicornucopia-nyuad-issue-tracker#12]
- Go to your profile. See image 1
 - Click on 'Ideas' on the left. See image 2

Oservable result:
 -  the field 'about yourself' keeps showing.

<img width="597" alt="screen shot 2017-03-10 at 00 44 07" src="https://cloud.githubusercontent.com/assets/5465723/23783610/cf859f70-052a-11e7-87f1-3c427765cac4.png">

<img width="637" alt="screen shot 2017-03-10 at 00 43 02" src="https://cloud.githubusercontent.com/assets/5465723/23783613/d405bbca-052a-11e7-98cb-988300cff4cc.png">

**Comment by fabriph** [comment]
This also happens if I browse the profile of someone else and then change to another page:

<img width="618" alt="screen shot 2017-03-10 at 00 59 34" src="https://cloud.githubusercontent.com/assets/5465723/23783924/ea2e6b20-052c-11e7-952c-f7d0f5a3ce1c.png">

**Comment by AVatch** [comment]
Thanks for pointing that out - it is fixed now.
