### ISSUE TITLE
Bug: pressing on a notification doesn't take me anywhere

### ISSUE THREAD

**Issue by fabriph** [AVatch/unicornucopia-nyuad-issue-tracker#6]
- Press the notification (see first attached image)
observable result: nothing happens (see second image)

<img width="937" alt="screen shot 2017-03-10 at 00 34 32" src="https://cloud.githubusercontent.com/assets/5465723/23783418/6bef7482-0529-11e7-8528-d0921dfc7c57.png">
<img width="1094" alt="screen shot 2017-03-10 at 00 33 14" src="https://cloud.githubusercontent.com/assets/5465723/23783419/6bf10a9a-0529-11e7-84d2-8445524c0c5d.png">

**Comment by AVatch** [comment]
Thanks for pointing this out - it has been fixed
